<?php

namespace ContainerVmNNibc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListaControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eseTpKi.App\Controller\ListaController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eseTpKi.App\\Controller\\ListaController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lista' => ['privates', '.errored..service_locator.eseTpKi.App\\Entity\\Lista', NULL, 'Cannot autowire service ".service_locator.eseTpKi": it needs an instance of "App\\Entity\\Lista" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lista' => 'App\\Entity\\Lista',
        ]))->withContext('App\\Controller\\ListaController::delete()', $container);
    }
}
