<?php

namespace ContainerVmNNibc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eseTpKi.App\Entity\Lista' shared service.
     *
     * @return \App\Entity\Lista
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eseTpKi": it needs an instance of "App\\Entity\\Lista" but this type has been excluded in "config/services.yaml".');
    }
}
