<?php

namespace ContainerVmNNibc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KGvZWZT.App\Controller\UsuarioController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KGvZWZT.App\\Controller\\UsuarioController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usuario' => ['privates', '.errored..service_locator.KGvZWZT.App\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.KGvZWZT": it needs an instance of "App\\Entity\\Usuario" but this type has been excluded in "config/services.yaml".'],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'usuario' => 'App\\Entity\\Usuario',
            'passwordHasher' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\UsuarioController::edit()', $container);
    }
}
