<?php

namespace ContainerS20Xaht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G7iP4uJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g7iP4uJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g7iP4uJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lista' => ['privates', '.errored..service_locator.g7iP4uJ.App\\Entity\\Lista', NULL, 'Cannot autowire service ".service_locator.g7iP4uJ": it needs an instance of "App\\Entity\\Lista" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'lista' => 'App\\Entity\\Lista',
            'serializer' => '?',
        ]);
    }
}
