<?php

namespace ContainerS20Xaht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VL10ixRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vL10ixR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vL10ixR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ListaController::index' => ['privates', '.service_locator.uQ9Ot44.App\\Controller\\ListaController::index()', 'getListaControllerindexService', true],
            'App\\Controller\\ListaController::new' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ListaController::new()', 'getListaControllernewService', true],
            'App\\Controller\\ListaController::show' => ['privates', '.service_locator.g7iP4uJ.App\\Controller\\ListaController::show()', 'getListaControllershowService', true],
            'App\\Controller\\ListaController::edit' => ['privates', '.service_locator.g7iP4uJ.App\\Controller\\ListaController::edit()', 'getListaControllereditService', true],
            'App\\Controller\\ListaController::delete' => ['privates', '.service_locator.eseTpKi.App\\Controller\\ListaController::delete()', 'getListaControllerdeleteService', true],
            'App\\Controller\\ListaController::compartilhar' => ['privates', '.service_locator.rqLfe30.App\\Controller\\ListaController::compartilhar()', 'getListaControllercompartilharService', true],
            'App\\Controller\\TarefaController::index' => ['privates', '.service_locator.IExv_Jo.App\\Controller\\TarefaController::index()', 'getTarefaControllerindexService', true],
            'App\\Controller\\TarefaController::new' => ['privates', '.service_locator.GL345QQ.App\\Controller\\TarefaController::new()', 'getTarefaControllernewService', true],
            'App\\Controller\\TarefaController::show' => ['privates', '.service_locator.2aydOaF.App\\Controller\\TarefaController::show()', 'getTarefaControllershowService', true],
            'App\\Controller\\TarefaController::edit' => ['privates', '.service_locator.2aydOaF.App\\Controller\\TarefaController::edit()', 'getTarefaControllereditService', true],
            'App\\Controller\\TarefaController::delete' => ['privates', '.service_locator.qGsI5Pk.App\\Controller\\TarefaController::delete()', 'getTarefaControllerdeleteService', true],
            'App\\Controller\\UsuarioController::index' => ['privates', '.service_locator.cYaxScO.App\\Controller\\UsuarioController::index()', 'getUsuarioControllerindexService', true],
            'App\\Controller\\UsuarioController::new' => ['privates', '.service_locator.2rSymSI.App\\Controller\\UsuarioController::new()', 'getUsuarioControllernewService', true],
            'App\\Controller\\UsuarioController::show' => ['privates', '.service_locator.Wuyw.pj.App\\Controller\\UsuarioController::show()', 'getUsuarioControllershowService', true],
            'App\\Controller\\UsuarioController::edit' => ['privates', '.service_locator.KGvZWZT.App\\Controller\\UsuarioController::edit()', 'getUsuarioControllereditService', true],
            'App\\Controller\\UsuarioController::delete' => ['privates', '.service_locator.KegljIe.App\\Controller\\UsuarioController::delete()', 'getUsuarioControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ListaController:index' => ['privates', '.service_locator.uQ9Ot44.App\\Controller\\ListaController::index()', 'getListaControllerindexService', true],
            'App\\Controller\\ListaController:new' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ListaController::new()', 'getListaControllernewService', true],
            'App\\Controller\\ListaController:show' => ['privates', '.service_locator.g7iP4uJ.App\\Controller\\ListaController::show()', 'getListaControllershowService', true],
            'App\\Controller\\ListaController:edit' => ['privates', '.service_locator.g7iP4uJ.App\\Controller\\ListaController::edit()', 'getListaControllereditService', true],
            'App\\Controller\\ListaController:delete' => ['privates', '.service_locator.eseTpKi.App\\Controller\\ListaController::delete()', 'getListaControllerdeleteService', true],
            'App\\Controller\\ListaController:compartilhar' => ['privates', '.service_locator.rqLfe30.App\\Controller\\ListaController::compartilhar()', 'getListaControllercompartilharService', true],
            'App\\Controller\\TarefaController:index' => ['privates', '.service_locator.IExv_Jo.App\\Controller\\TarefaController::index()', 'getTarefaControllerindexService', true],
            'App\\Controller\\TarefaController:new' => ['privates', '.service_locator.GL345QQ.App\\Controller\\TarefaController::new()', 'getTarefaControllernewService', true],
            'App\\Controller\\TarefaController:show' => ['privates', '.service_locator.2aydOaF.App\\Controller\\TarefaController::show()', 'getTarefaControllershowService', true],
            'App\\Controller\\TarefaController:edit' => ['privates', '.service_locator.2aydOaF.App\\Controller\\TarefaController::edit()', 'getTarefaControllereditService', true],
            'App\\Controller\\TarefaController:delete' => ['privates', '.service_locator.qGsI5Pk.App\\Controller\\TarefaController::delete()', 'getTarefaControllerdeleteService', true],
            'App\\Controller\\UsuarioController:index' => ['privates', '.service_locator.cYaxScO.App\\Controller\\UsuarioController::index()', 'getUsuarioControllerindexService', true],
            'App\\Controller\\UsuarioController:new' => ['privates', '.service_locator.2rSymSI.App\\Controller\\UsuarioController::new()', 'getUsuarioControllernewService', true],
            'App\\Controller\\UsuarioController:show' => ['privates', '.service_locator.Wuyw.pj.App\\Controller\\UsuarioController::show()', 'getUsuarioControllershowService', true],
            'App\\Controller\\UsuarioController:edit' => ['privates', '.service_locator.KGvZWZT.App\\Controller\\UsuarioController::edit()', 'getUsuarioControllereditService', true],
            'App\\Controller\\UsuarioController:delete' => ['privates', '.service_locator.KegljIe.App\\Controller\\UsuarioController::delete()', 'getUsuarioControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ListaController::index' => '?',
            'App\\Controller\\ListaController::new' => '?',
            'App\\Controller\\ListaController::show' => '?',
            'App\\Controller\\ListaController::edit' => '?',
            'App\\Controller\\ListaController::delete' => '?',
            'App\\Controller\\ListaController::compartilhar' => '?',
            'App\\Controller\\TarefaController::index' => '?',
            'App\\Controller\\TarefaController::new' => '?',
            'App\\Controller\\TarefaController::show' => '?',
            'App\\Controller\\TarefaController::edit' => '?',
            'App\\Controller\\TarefaController::delete' => '?',
            'App\\Controller\\UsuarioController::index' => '?',
            'App\\Controller\\UsuarioController::new' => '?',
            'App\\Controller\\UsuarioController::show' => '?',
            'App\\Controller\\UsuarioController::edit' => '?',
            'App\\Controller\\UsuarioController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ListaController:index' => '?',
            'App\\Controller\\ListaController:new' => '?',
            'App\\Controller\\ListaController:show' => '?',
            'App\\Controller\\ListaController:edit' => '?',
            'App\\Controller\\ListaController:delete' => '?',
            'App\\Controller\\ListaController:compartilhar' => '?',
            'App\\Controller\\TarefaController:index' => '?',
            'App\\Controller\\TarefaController:new' => '?',
            'App\\Controller\\TarefaController:show' => '?',
            'App\\Controller\\TarefaController:edit' => '?',
            'App\\Controller\\TarefaController:delete' => '?',
            'App\\Controller\\UsuarioController:index' => '?',
            'App\\Controller\\UsuarioController:new' => '?',
            'App\\Controller\\UsuarioController:show' => '?',
            'App\\Controller\\UsuarioController:edit' => '?',
            'App\\Controller\\UsuarioController:delete' => '?',
        ]);
    }
}
