<?php

namespace ContainerS20Xaht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListaControllercompartilharService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rqLfe30.App\Controller\ListaController::compartilhar()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rqLfe30.App\\Controller\\ListaController::compartilhar()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lista' => ['privates', '.errored..service_locator.rqLfe30.App\\Entity\\Lista', NULL, 'Cannot autowire service ".service_locator.rqLfe30": it needs an instance of "App\\Entity\\Lista" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'lista' => 'App\\Entity\\Lista',
            'em' => '?',
        ]))->withContext('App\\Controller\\ListaController::compartilhar()', $container);
    }
}
