<?php

namespace ContainerS20Xaht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLista3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rqLfe30.App\Entity\Lista' shared service.
     *
     * @return \App\Entity\Lista
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rqLfe30": it needs an instance of "App\\Entity\\Lista" but this type has been excluded in "config/services.yaml".');
    }
}
