<?php

namespace ContainerS20Xaht;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTarefaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2aydOaF.App\Entity\Tarefa' shared service.
     *
     * @return \App\Entity\Tarefa
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2aydOaF": it needs an instance of "App\\Entity\\Tarefa" but this type has been excluded in "config/services.yaml".');
    }
}
